In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
df = pd.read_parquet('pcd_usgs_9_sites_laz.parquet')

In [3]:
df

,workunit,description,quality_level,dem_gsd_m,urls,urls_count,area_km2,geometry
0,WY_FEMA_East_B9_2019,glaciers / mountainous,QL 2,1.00,[https://rockyweb.usgs.gov/vdelivery/Datasets/...,773,681.061890,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x1c\x00...
1,CO_WestCentral_2019,coniferous / mountainous,QL 2,1.00,[https://rockyweb.usgs.gov/vdelivery/Datasets/...,238,183.591995,b'\x01\x06\x00\x00\x00\x02\x00\x00\x00\x01\x03...
2,TX_DesertMountains_B1_2018,shrubland / grassland,QL 2,1.00,[https://rockyweb.usgs.gov/vdelivery/Datasets/...,100,164.537033,b'\x01\x06\x00\x00\x00\x02\x00\x00\x00\x01\x03...
3,CA_YosemiteNP_2019,coniferous / mountainous,QL 1,0.50,[https://rockyweb.usgs.gov/vdelivery/Datasets/...,106,83.577324,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00j2\x00\x...
4,GA_Central_3_2019,mixed lulc,QL 2,1.00,[https://rockyweb.usgs.gov/vdelivery/Datasets/...,857,744.736328,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x1f\x00...
5,WI_Brown_2_2020,urban / wetlands,QL 1,0.50,[https://rockyweb.usgs.gov/vdelivery/Datasets/...,58,89.068001,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x10\x00...
6,NE_Northeast_Phase2_2_2020,cropland,QL 2,1.00,[https://rockyweb.usgs.gov/vdelivery/Datasets/...,606,539.823303,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00h\x03\x0...
7,AZ_PimaCo_2_2021,desert / mine,QL 1,0.50,[https://rockyweb.usgs.gov/vdelivery/Datasets/...,69,53.211098,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\r\x00\x...
8,CA_SanFrancisco_1_B23,urban,QL 0,0.25,[https://rockyweb.usgs.gov/vdelivery/Datasets/...,244,55.372066,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\xd9r\x0...

In [4]:
ls *20250709_*

20250709_PCD_3dep_als_footprints.geojson
20250709_PCD_3dep_als_footprints.parquet
20250709_PCD_3dep_fourway_overlap.geojson
20250709_PCD_3dep_gedi_tracks.geojson
20250709_PCD_3dep_is2_tracks.geojson
20250709_PCD_3dep_stereo_footprints.geojson

In [6]:
als_footprints_data = gpd.read_file('20250709_PCD_3dep_als_footprints.geojson')
gedi_track_data = gpd.read_file('20250709_PCD_3dep_gedi_tracks.geojson')
is2_data = gpd.read_file('20250709_PCD_3dep_is2_tracks.geojson')
stereo_data = gpd.read_file('20250709_PCD_3dep_stereo_footprints.geojson')

In [7]:
als_footprints_data

,usgs_workunit,description,start_datetime,end_datetime,ql,sensor,wavelength_nm,avg_point_density_m2,first_return_point_density_m2,ground_return_point_density_m2,horizontal_accuracy_95_m,nva_95_m,vva_95_m,geometry
0,WY_FEMA_East_B9_2019,glaciers / mountainous,2019-07-26,2019-09-22,QL 2,Leica Terrain Mapper and Optech Galaxy PRIME,1064,2.0000,NaN,NaN,0.636,0.1960,0.3000,"POLYGON ((-108.7677 42.8813, -108.7921 42.8789..."
1,CO_WestCentral_2019,coniferous / mountainous,2019-08-21,2019-09-19,QL 2,Riegl VQ1560i,1064,NaN,6.250000,2.320000,0.015,0.0980,0.2870,"POLYGON ((-106.13571 38.4146, -106.1702 38.411..."
2,TX_DesertMountains_B1_2018,shrubland / grassland,2019-09-11,2019-10-20,QL 2,Optech Galaxy Prime,1064,2.9400,NaN,NaN,NaN,0.1330,0.2310,"POLYGON ((-106.2194 31.7337, -106.2196 31.7338..."
3,CA_YosemiteNP_2019,coniferous / mountainous,2019-10-07,2019-10-23,QL 1,Reigl VQ-1560i,1064,NaN,23.410000,3.890000,0.130,0.1030,0.2290,"POLYGON ((-119.82253 37.65666, -119.82253 37.6..."
4,GA_Central_3_2019,mixed lulc,2020-02-02,2020-03-28,QL 2,Optech Galaxy Prime,1064,3.1917,NaN,NaN,NaN,0.1401,0.2854,"POLYGON ((-84.21686 31.22133, -84.21603 31.227..."
5,WI_Brown_2_2020,urban / wetlands,2020-05-07,2020-05-07,QL 1,Riegl VQ1560ii,1550,8.0000,NaN,NaN,0.190,0.0517,0.0630,"POLYGON ((-88.25061 44.68788, -88.25036 44.687..."
6,NE_Northeast_Phase2_2_2020,cropland,2020-11-16,2020-12-09,QL 2,Galaxy Prime T2000,1064,2.0000,NaN,NaN,0.584,0.0715,0.1710,"POLYGON ((-97.09994 41.74402, -97.09952 41.744..."
7,AZ_PimaCo_2_2021,desert / mine,2021-09-27,2021-11-17,QL 1,"Riegl VQ1560i, VQ 1560ii, and Optech Galaxy T2000",1064,8.0000,NaN,NaN,0.190,0.1058,0.1466,"MULTIPOLYGON (((-111.67147 31.52216, -111.6714..."
8,CA_SanFrancisco_1_B23,urban,2023-04-20,2023-04-20,QL 0,Riegl VQ1560ii,1550,50.0000,90.099998,40.799999,0.120,0.0318,0.1189,"MULTIPOLYGON (((-122.36022 37.71341, -122.3602..."

In [8]:
gedi_track_data

,usgs_workunit,gedi_granule_id,date,geometry
0,WY_FEMA_East_B9_2019,GEDI02_A_2019194055411_O03298_02_T00155_02_003...,2019-07-13,"POLYGON ((-108.81488 43.53466, -110.12724 42.8..."
1,WY_FEMA_East_B9_2019,GEDI02_A_2019200084834_O03393_03_T03035_02_003...,2019-07-19,"POLYGON ((-110.15856 43.88066, -110.12591 43.9..."
2,WY_FEMA_East_B9_2019,GEDI02_A_2019209000122_O03527_02_T04730_02_003...,2019-07-28,"POLYGON ((-108.60324 43.42745, -109.88604 42.7..."
3,WY_FEMA_East_B9_2019,GEDI02_A_2019211043557_O03561_03_T00847_02_003...,2019-07-30,"POLYGON ((-110.50391 43.40751, -110.47131 43.4..."
4,WY_FEMA_East_B9_2019,GEDI02_A_2019219194832_O03695_02_T03965_02_003...,2019-08-07,"POLYGON ((-108.78088 43.87286, -110.50504 43.0..."
...,...,...,...,...
61,AZ_PimaCo_2_2021,GEDI02_A_2021261011319_O15667_02_T08065_02_003...,2021-09-18,"POLYGON ((-111.42863 31.73016, -111.65446 31.5..."
62,AZ_PimaCo_2_2021,GEDI02_A_2021264234230_O15728_02_T10605_02_003...,2021-09-21,"POLYGON ((-110.81668 32.73718, -111.82736 31.8..."
63,AZ_PimaCo_2_2021,GEDI02_A_2021285225842_O16053_03_T08636_02_003...,2021-10-12,"POLYGON ((-111.48451 32.72825, -111.36148 32.7..."
64,AZ_PimaCo_2_2021,GEDI02_A_2021332204942_O16780_02_T08218_02_003...,2021-11-28,"POLYGON ((-110.97813 31.88991, -111.31838 31.5..."
65,CA_SanFrancisco_1_B23,GEDI02_A_2023028212552_O23387_02_T09397_02_003...,2023-01-28,"POLYGON ((-122.57657 37.62515, -122.57727 37.7..."

In [10]:
stereo_data

,usgs_workunit,id,datetime,collection,geolocation_uncertainty,gsd,target_to_spacecraft_elevation_avg,view:azimuth,view:off_nadir,view:sun_azimuth,view:sun_elevation,geometry
0,WY_FEMA_East_B9_2019,1020010086976A00,2019-08-17 21:25:58.386000+00:00,wv01,8.135253,0.650055,56.800164,46.962612,30.533567,231.326150,50.161998,"POLYGON ((-109.70664 43.57756, -109.70831 43.5..."
1,WY_FEMA_East_B9_2019,1020010089403600,2019-08-17 21:25:07.836000+00:00,wv01,7.649597,0.568135,66.267356,136.898139,21.926126,231.037034,50.260158,"POLYGON ((-109.68461 43.58562, -109.68484 43.5..."
2,CO_WestCentral_2019,102001008BD60800,2019-09-30 20:55:29.358000+00:00,wv01,7.518990,0.546097,69.943833,317.018132,18.552592,220.605829,40.470560,"POLYGON ((-106.79232 39.02773, -106.79092 38.9..."
3,CO_WestCentral_2019,1020010088168700,2019-09-30 20:54:39.207000+00:00,wv01,8.927096,0.649771,56.454620,219.950260,30.843899,220.361555,40.572175,"POLYGON ((-106.80822 39.01663, -106.80613 38.9..."
4,TX_DesertMountains_B1_2018,1030010097D5CC00,2019-08-28 17:42:08.128000+00:00,wv02,5.992387,0.608630,55.561563,319.023146,30.303720,134.334512,61.152921,"POLYGON ((-105.84239 31.99968, -105.84204 31.9..."
5,TX_DesertMountains_B1_2018,10300100984A3A00,2019-08-28 17:40:50.529000+00:00,wv02,6.472707,0.598300,56.261114,249.314471,29.707987,133.781532,60.977976,"POLYGON ((-105.84715 31.96531, -105.84698 31.9..."
6,CA_YosemiteNP_2019,102001008E543300,2019-10-06 21:51:17.444000+00:00,wv01,5.756522,0.528064,73.888030,356.171066,14.921082,220.956310,37.832267,"POLYGON ((-119.58596 38.41426, -119.5858 38.36..."
7,CA_YosemiteNP_2019,102001008EE06B00,2019-10-06 21:50:39.043000+00:00,wv01,6.182957,0.536693,71.632215,206.465758,17.000279,220.782356,37.912517,"POLYGON ((-119.58754 38.41427, -119.58775 38.3..."
8,GA_Central_3_2019,10300100A26FD700,2020-02-09 16:26:28.697000+00:00,wv02,1.925603,0.560759,60.862231,9.301677,25.749892,153.261732,39.779173,"POLYGON ((-84.13481 31.95756, -84.13457 31.902..."
9,GA_Central_3_2019,10300100A132F900,2020-02-09 16:25:11.447000+00:00,wv02,2.284359,0.476302,78.655265,203.004258,10.248807,152.885173,39.687845,"POLYGON ((-84.12347 31.03196, -84.12349 30.989..."
10,WI_Brown_2_2020,104001005ACC6E00,2020-05-02 16:53:39.259000+00:00,wv03-vnir,20.828249,0.361248,63.932065,338.203730,23.620462,153.507360,58.991155,"POLYGON ((-88.08721 44.64458, -88.08709 44.610..."
11,WI_Brown_2_2020,104001005B461800,2020-05-02 16:52:41.609000+00:00,wv03-vnir,20.170746,0.347557,67.174576,235.594695,20.714276,153.087095,58.912151,"POLYGON ((-88.08848 44.63627, -88.08834 44.605..."
12,NE_Northeast_Phase2_2_2020,10200100A1228A00,2020-12-09 20:18:48.832000+00:00,wv01,7.597288,0.638003,57.931660,321.285801,29.510591,208.006988,21.523126,"POLYGON ((-98.36916 41.05472, -98.36845 40.994..."
13,NE_Northeast_Phase2_2_2020,102001009D48BC00,2020-12-09 20:17:52.882000+00:00,wv01,7.830697,0.660007,55.656969,238.530060,31.562793,207.790417,21.587410,"POLYGON ((-98.37576 41.01407, -98.37561 40.959..."
14,NE_Northeast_Phase2_2_2020,10200100A0BEE600,2020-11-26 20:23:42.089000+00:00,wv01,7.572910,0.635046,58.112389,342.233906,29.346482,210.862477,21.328275,"POLYGON ((-98.36149 42.0395, -98.36076 41.9752..."
15,NE_Northeast_Phase2_2_2020,10200100A0A9E600,2020-11-26 20:22:50.989000+00:00,wv01,6.898459,0.554880,68.371677,244.050934,19.998001,210.677060,21.428112,"POLYGON ((-98.35173 42.01213, -98.35159 41.964..."
16,AZ_PimaCo_2_2021,104001006D788E00,2021-09-20 18:20:15.204000+00:00,wv03-vnir,23.293823,0.401764,56.492126,36.276095,30.222437,153.594822,56.272900,"POLYGON ((-111.14081 31.91698, -111.14069 31.8..."
17,AZ_PimaCo_2_2021,104001006E942500,2021-09-20 18:19:20.355000+00:00,wv03-vnir,18.983706,0.325564,74.364589,120.185198,14.225722,153.213495,56.189721,"POLYGON ((-111.12609 31.9272, -111.12612 31.89..."
18,CA_SanFrancisco_1_B23,10200100DE097E00,2023-07-15 22:11:14.115000+00:00,wv01,4.018339,0.651991,56.178333,45.332539,30.977234,245.251042,60.348070,"POLYGON ((-122.57841 38.00988, -122.57842 37.9..."
19,CA_SanFrancisco_1_B23,10200100DC70E900,2023-07-15 22:10:27.264000+00:00,wv01,4.093067,0.554889,68.113649,128.413938,20.343934,245.031167,60.490509,"POLYGON ((-122.55729 38.02073, -122.55742 37.9..."

In [11]:
ls *neon*als*geojson

20250718_PCD_neon_als_footprints.geojson

In [12]:
neon_als_footprints_data = gpd.read_file('20250718_PCD_neon_als_footprints.geojson')

In [13]:
neon_als_footprints_data

,neon_id,description,start_datetime,end_datetime,sensor,wavelength_nm,avg_point_density_m2,ground_return_point_density_m2,horizontal_uncertainty_avg_m,vertical_uncertainty_avg_m,geometry
0,BART,mixed hardwood forest,2019-08-25 14:05:12+00:00,2019-08-25 19:20:01+00:00,ALTM Gemini,1064,5.9,2.3,0.5,0.13,"POLYGON ((-71.22225 43.98755, -71.31731 43.988..."
1,REDB,deciduous conifer mix,2021-05-20 07:00:00+00:00,2021-05-21 06:59:59+00:00,RIEGL LMS-Q780,1064,17,7,0.19,0.088,"POLYGON ((-111.79348 40.76534, -111.79713 40.7..."
2,WREF,conifer forest,2019-07-12 08:00:00+00:00,2019-07-15 07:59:59+00:00,RIEGL LMS-Q780,1064,18,3,0.19,0.1,"MULTIPOLYGON (((-122.03336 45.77725, -122.0346..."

In [16]:
ncalm_sfm_footprint = gpd.read_file('20250722_PCD_ncalm_sfm_footprints.geojson')

In [17]:
ncalm_sfm_footprint

,ncalm_id,description,start_datetime,end_datetime,sensor,wavelength_nm,avg_point_density_m2,ground_return_point_density_m2,horizontal_uncertainty_avg_m,vertical_uncertainty_avg_m,geometry
0,OTLAS.092021.32611.1,fault,2020-02-15,2020-02-18,S.O.D.A. Camera (SfM),None,192.36,None,0.019,0.033,"POLYGON ((-115.73157 33.35367, -115.73451 33.3..."

In [21]:
stereo_neon_data = gpd.read_file('20250718_PCD_neon_stereo_footprints.geojson')

In [22]:
stereo_neon_data

,neon_id,id,datetime,collection,geolocation_uncertainty,gsd,target_to_spacecraft_elevation_avg,view:azimuth,view:off_nadir,view:sun_azimuth,view:sun_elevation,geometry
0,BART,10300100988FA400,2019-09-22,wv02,5.413742,0.594930,57.003916,336.312474,28.907354,158.581430,44.947742,"POLYGON ((-71.47527 44.00459, -71.47559 43.969..."
1,BART,1030010098464200,2019-09-22,wv02,5.995574,0.533047,64.970699,251.099085,22.233532,158.147597,44.839812,"POLYGON ((-71.47176 43.93816, -71.47176 43.937..."
2,BART,1030010093B2F600,2019-06-10,wv02,5.779450,0.544419,63.237935,72.668828,23.689538,158.141565,67.502660,"POLYGON ((-71.22802 44.96636, -71.22654 44.920..."
3,BART,1030010092D6AF00,2019-06-10,wv02,7.990128,0.617548,54.739817,157.351159,31.002152,157.332847,67.443661,"POLYGON ((-71.2245 44.98526, -71.22444 44.9279..."
4,REDB,10200100B1301200,2021-06-04,wv01,6.996440,0.618050,59.866083,354.106052,27.761672,241.196497,60.192563,"POLYGON ((-111.98506 40.9671, -111.98453 40.90..."
5,REDB,10200100B1172E00,2021-06-04,wv01,6.445797,0.547035,69.989205,222.234455,18.512119,240.891613,60.345171,"POLYGON ((-111.9792 40.95336, -111.97908 40.90..."
6,REDB,10200100B1551C00,2021-05-22,wv01,6.029474,0.528095,74.606667,8.956553,14.258043,240.091210,57.958786,"POLYGON ((-111.97111 40.95434, -111.97093 40.9..."
7,REDB,10200100B1630600,2021-05-22,wv01,7.117176,0.582732,64.043286,194.791307,23.960539,239.832227,58.091383,"POLYGON ((-111.97892 40.95493, -111.97898 40.9..."
8,WREF,10300100965CBA00,2019-07-24,wv02,5.693468,0.546416,63.151442,340.298395,23.763541,145.939672,61.005277,"POLYGON ((-122.23396 45.97923, -122.2338 45.92..."
9,WREF,10300100962F3500,2019-07-24,wv02,6.257399,0.513225,68.630450,241.188880,18.973471,145.441645,60.874778,"POLYGON ((-122.2328 45.9662, -122.23292 45.921..."

In [23]:
stereo_ncalm_data = gpd.read_file('20250722_PCD_ncalm_stereo_footprints.geojson')

In [24]:
stereo_ncalm_data

,ncalm_id,id,datetime,collection,geolocation_uncertainty,gsd,target_to_spacecraft_elevation_avg,view:azimuth,view:off_nadir,view:sun_azimuth,view:sun_elevation,geometry
0,OTLAS.092021.32611.1,10300100A178D600,2020-01-31,wv02,2.121252,0.464631,86.706828,118.784715,3.009589,156.413705,35.909457,"POLYGON ((-115.78093 33.94113, -115.78087 33.9..."
1,OTLAS.092021.32611.1,10300100A3456700,2020-01-31,wv02,2.641926,0.583624,58.081182,188.818980,28.298882,156.144341,35.789016,"POLYGON ((-115.79298 33.9843, -115.79312 33.96..."